name: Build and Deploy app

on:
  push:
    branches:
      - devops 

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy Nodejs app
        uses: appleboy/ssh-action@v0.1.2
        with:
          host: ${{ secrets.SSH_HOST }}
          key: ${{ secrets.SSH_KEY }}
          username: ${{ secrets.SSH_USERNAME }}

      - name: Create Directories
        run: |
          ssh ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }} "mkdir -p /var/www/staging.thdctech.com/home-site"

      - name: Clone GitHub Repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          submodules: 'recursive'

      - name: Setup Project
        run: |
          cd /var/www/staging.thdctech.com/home-site
          git clone git@github.com:thdctech/home-site.git
          echo 'Deployment successful to DO'


         
           