name: Deploy and Build 
on: 
  push:
    branches:
      - devops 

jobs: 
  deploy:
    runs-on: ubuntu-latest
    steps: 
      - name: Deploy on digital ocean 
        uses: appleboy/ssh-action@v.0.1.2
        with: 
          host: ${{ secrets.SSH_HOST }}
          key: ${{ secrets.SSH_KEY }}
          username: ${{ secrets.SSH_USERNAME }}
   

        script: |
            cd /var/www/staging.thdctech.com
            git clone git@github.com:thdctech/home-site.git
            echo 'Deployment successful'
         

         
    