name: Deploy sveltekit

on:
  push:
    branches: 
      - devops
  

jobs:
  build:
    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [16.x]  

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - run: cd /var/www/staging.thdctech.com/actions-runner/_work/home-site/home-site
    - run: npm install
    - run: npm run build

    - name: Copy build output to deployment directory
      run: cp -r /var/www/staging.thdctech.com/actions-runner/_work/home-site/home-site/build /var/www/staging.thdctech.com/home-site

    # Install PM2 globally
    - name: Install PM2
      run: npm install -g pm2

    # Start or restart the SvelteKit application using PM2
    - name: Start or Restart SvelteKit with PM2
      run: pm2 restart 0

    # Restart Nginx

    - name: Restart Nginx
      run: sudo service nginx restart



         
           