name: Deploy and Build 
on: 
  push:
    branches:
      - devops 

jobs: 
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: executing remote ssh commands using ssh key 
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
      - name: Run a command with sudo 
        run: |
          echo "${{ secrets.SUDO_PASSWORD }} | 
          sudo -S cd /var/www/staging.thdctech.com"
          sudo git clone git@github.com:thdctech/home-site.git
        env: 
          SUDO_PASSWORD: ${{ secrets.SUDO_PASSWORD}}
          
      

         
    