name: Build and deploy
on: 
  push: 
    branches:
      - devops 
jobs: 
  deploy: 
    runs-on: ubuntu-latest
    steps: 
      - name: Deploy Node.js app
        uses: appleboy/ssh-action@v0.1.2
        with: 
          host: ${{ secrets.SSH_HOST }}
          key: ${{ secrets.SSH_KEY }}
          username: ${{ secrets.SSH_USERNAME }}

          script: |
            mkdir homesite
            cd homesite
            git clone git@github.com:thdctech/home-site.git
            echo 'Deployment successful'
          
      

         
    