name: Build and Deploy app
on: 
  push:
    branches:
      - devops 

jobs: 
  deploy: 
    runs-on: ubuntu-latest
    steps: 
      - name: Deploy Nodejs app
        uses: appleboy/ssh-action@v0.1.2
        with:
          host: ${{ secrets.SSH_HOST }}
          key: ${{ secrets.SSH_KEY }}
          username: ${{ secrets.SSH_USERNAME }}

          script: |
            mkdir home-site
            cd home-site
            git clone git@github.com:thdctech/home-site.git
            echo 'Deployment successful to DO'